# render.yaml
services:
  - name: seaside-frontend
    type: web
    runtime: static
    repo: https://github.com/Seaside-Sustainability-Web-GIS/TRASH-frontend.git
    branch: Deploy
    autoDeploy: true
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    region: oregon
    pullRequestPreviews: true
    healthCheckPath: /